### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by rrreeeyyy** [matsumoto-r/rcon#3]
Thank you for creating awesome tool, I like it.

So, we would like to use release binary on github, like this.
- https://github.com/hsbt/mackerel-plugin-sidekiq-job-count/releases/tag/v0.0.3

Could you release `rcon` binary on somewhere?

FYI: I think this rake task and `ghr` as a good reference for release mruby-cli binary.

- https://github.com/hsbt/mackerel-plugin-sidekiq-job-count/blob/5313203158a84f0d5ce737d8fd187be6bf81cc02/Rakefile#L68-L89
- https://github.com/tcnksm/ghr

**Comment by matsumoto-r** [comment]
I also think release binary is useful. But, I'm newbie for ghr. Could you send the PR? I would like to merge your idea.

**Comment by matsumoto-r** [comment]
@rrreeeyyy I'm trying to implement this binary release. Please check after creating PR! Thanks.

**Comment by rrreeeyyy** [comment]
Closed by #4 with awesome works. Thanks!
